# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/MLP/MLP.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MLP || ORIG_REF_NAME==MLP} -quiet] -quiet

# IP: bd/MLP/ip/MLP_processing_system7_0_0/MLP_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MLP_processing_system7_0_0 || ORIG_REF_NAME==MLP_processing_system7_0_0} -quiet] -quiet

# IP: bd/MLP/ip/MLP_IP_psds_0_0/MLP_IP_psds_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MLP_IP_psds_0_0 || ORIG_REF_NAME==MLP_IP_psds_0_0} -quiet] -quiet

# IP: bd/MLP/ip/MLP_ps7_0_axi_periph_0/MLP_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MLP_ps7_0_axi_periph_0 || ORIG_REF_NAME==MLP_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/MLP/ip/MLP_rst_ps7_0_50M_0/MLP_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MLP_rst_ps7_0_50M_0 || ORIG_REF_NAME==MLP_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/MLP/ip/MLP_auto_pc_0/MLP_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MLP_auto_pc_0 || ORIG_REF_NAME==MLP_auto_pc_0} -quiet] -quiet

# XDC: /home/student/Desktop/PSDS_FINALNA/IP_mina_opacic/IP_mina_opacic.gen/sources_1/bd/MLP/MLP_ooc.xdc
