# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mina/Downloads/IP_JEZGRO/IP_JEZGRO.srcs/sources_1/bd/design_MLP/ip/design_MLP_rst_ps7_0_50M_0/design_MLP_rst_ps7_0_50M_0.xci
# IP: The module: 'design_MLP_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mina/Downloads/IP_JEZGRO/IP_JEZGRO.gen/sources_1/bd/design_MLP/ip/design_MLP_rst_ps7_0_50M_0/design_MLP_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_MLP_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/mina/Downloads/IP_JEZGRO/IP_JEZGRO.gen/sources_1/bd/design_MLP/ip/design_MLP_rst_ps7_0_50M_0/design_MLP_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_MLP_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/mina/Downloads/IP_JEZGRO/IP_JEZGRO.gen/sources_1/bd/design_MLP/ip/design_MLP_rst_ps7_0_50M_0/design_MLP_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_MLP_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/mina/Downloads/IP_JEZGRO/IP_JEZGRO.srcs/sources_1/bd/design_MLP/ip/design_MLP_rst_ps7_0_50M_0/design_MLP_rst_ps7_0_50M_0.xci
# IP: The module: 'design_MLP_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mina/Downloads/IP_JEZGRO/IP_JEZGRO.gen/sources_1/bd/design_MLP/ip/design_MLP_rst_ps7_0_50M_0/design_MLP_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_MLP_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/mina/Downloads/IP_JEZGRO/IP_JEZGRO.gen/sources_1/bd/design_MLP/ip/design_MLP_rst_ps7_0_50M_0/design_MLP_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_MLP_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/mina/Downloads/IP_JEZGRO/IP_JEZGRO.gen/sources_1/bd/design_MLP/ip/design_MLP_rst_ps7_0_50M_0/design_MLP_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_MLP_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
