# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/MLP1/MLP1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MLP1 || ORIG_REF_NAME==MLP1} -quiet] -quiet

# IP: bd/MLP1/ip/MLP1_processing_system7_0_0/MLP1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MLP1_processing_system7_0_0 || ORIG_REF_NAME==MLP1_processing_system7_0_0} -quiet] -quiet

# IP: bd/MLP1/ip/MLP1_IP_0_1/MLP1_IP_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MLP1_IP_0_1 || ORIG_REF_NAME==MLP1_IP_0_1} -quiet] -quiet

# IP: bd/MLP1/ip/MLP1_auto_pc_0/MLP1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MLP1_auto_pc_0 || ORIG_REF_NAME==MLP1_auto_pc_0} -quiet] -quiet

# IP: bd/MLP1/ip/MLP1_ps7_0_axi_periph_0/MLP1_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MLP1_ps7_0_axi_periph_0 || ORIG_REF_NAME==MLP1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/MLP1/ip/MLP1_rst_ps7_0_50M_0/MLP1_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MLP1_rst_ps7_0_50M_0 || ORIG_REF_NAME==MLP1_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: /home/mina/Downloads/IP_NOV0/IP_NOV0.gen/sources_1/bd/MLP1/MLP1_ooc.xdc
