# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/student/Downloads/psds/PSDS_FINALNA/IP_psds_8_9/IP_psds_8_9.srcs/sources_1/bd/psds/ip/psds_processing_system7_0_0/psds_processing_system7_0_0.xci
# IP: The module: 'psds_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/student/Downloads/psds/PSDS_FINALNA/IP_psds_8_9/IP_psds_8_9.gen/sources_1/bd/psds/ip/psds_processing_system7_0_0/psds_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'psds_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/student/Downloads/psds/PSDS_FINALNA/IP_psds_8_9/IP_psds_8_9.srcs/sources_1/bd/psds/ip/psds_processing_system7_0_0/psds_processing_system7_0_0.xci
# IP: The module: 'psds_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/student/Downloads/psds/PSDS_FINALNA/IP_psds_8_9/IP_psds_8_9.gen/sources_1/bd/psds/ip/psds_processing_system7_0_0/psds_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'psds_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
