# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/student/Desktop/PSDS_FINALNA/IP_mina_opacic/IP_mina_opacic.srcs/sources_1/bd/MLP/ip/MLP_rst_ps7_0_50M_0/MLP_rst_ps7_0_50M_0.xci
# IP: The module: 'MLP_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/student/Desktop/PSDS_FINALNA/IP_mina_opacic/IP_mina_opacic.gen/sources_1/bd/MLP/ip/MLP_rst_ps7_0_50M_0/MLP_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MLP_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/student/Desktop/PSDS_FINALNA/IP_mina_opacic/IP_mina_opacic.gen/sources_1/bd/MLP/ip/MLP_rst_ps7_0_50M_0/MLP_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MLP_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/student/Desktop/PSDS_FINALNA/IP_mina_opacic/IP_mina_opacic.gen/sources_1/bd/MLP/ip/MLP_rst_ps7_0_50M_0/MLP_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MLP_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/student/Desktop/PSDS_FINALNA/IP_mina_opacic/IP_mina_opacic.srcs/sources_1/bd/MLP/ip/MLP_rst_ps7_0_50M_0/MLP_rst_ps7_0_50M_0.xci
# IP: The module: 'MLP_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/student/Desktop/PSDS_FINALNA/IP_mina_opacic/IP_mina_opacic.gen/sources_1/bd/MLP/ip/MLP_rst_ps7_0_50M_0/MLP_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'MLP_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/student/Desktop/PSDS_FINALNA/IP_mina_opacic/IP_mina_opacic.gen/sources_1/bd/MLP/ip/MLP_rst_ps7_0_50M_0/MLP_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MLP_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/student/Desktop/PSDS_FINALNA/IP_mina_opacic/IP_mina_opacic.gen/sources_1/bd/MLP/ip/MLP_rst_ps7_0_50M_0/MLP_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MLP_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
