# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/psds/psds.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==psds || ORIG_REF_NAME==psds} -quiet] -quiet

# IP: bd/psds/ip/psds_processing_system7_0_0/psds_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==psds_processing_system7_0_0 || ORIG_REF_NAME==psds_processing_system7_0_0} -quiet] -quiet

# IP: bd/psds/ip/psds_ps7_0_axi_periph_0/psds_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==psds_ps7_0_axi_periph_0 || ORIG_REF_NAME==psds_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/psds/ip/psds_rst_ps7_0_50M_0/psds_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==psds_rst_ps7_0_50M_0 || ORIG_REF_NAME==psds_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/psds/ip/psds_ip_mlp_0_1/psds_ip_mlp_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==psds_ip_mlp_0_1 || ORIG_REF_NAME==psds_ip_mlp_0_1} -quiet] -quiet

# IP: bd/psds/ip/psds_auto_pc_0/psds_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==psds_auto_pc_0 || ORIG_REF_NAME==psds_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/student/Downloads/psds/PSDS_FINALNA/IP_psds_8_9/IP_psds_8_9.gen/sources_1/bd/psds/psds_ooc.xdc
