# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_MLP/design_MLP.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_MLP || ORIG_REF_NAME==design_MLP} -quiet] -quiet

# IP: bd/design_MLP/ip/design_MLP_processing_system7_0_0/design_MLP_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_MLP_processing_system7_0_0 || ORIG_REF_NAME==design_MLP_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_MLP/ip/design_MLP_IP_0_1/design_MLP_IP_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_MLP_IP_0_1 || ORIG_REF_NAME==design_MLP_IP_0_1} -quiet] -quiet

# IP: bd/design_MLP/ip/design_MLP_ps7_0_axi_periph_0/design_MLP_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_MLP_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_MLP_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_MLP/ip/design_MLP_rst_ps7_0_50M_0/design_MLP_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_MLP_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_MLP_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_MLP/ip/design_MLP_auto_pc_0/design_MLP_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_MLP_auto_pc_0 || ORIG_REF_NAME==design_MLP_auto_pc_0} -quiet] -quiet

# XDC: /home/mina/Downloads/IP_JEZGRO/IP_JEZGRO.gen/sources_1/bd/design_MLP/design_MLP_ooc.xdc
