#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Sep 06 11:16:24 CEST 2023
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 7b8557f81daf4ebc97a1815de1703bb9 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot MLP_behav xil_defaultlib.MLP -log elaborate.log"
xelab -wto 7b8557f81daf4ebc97a1815de1703bb9 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot MLP_behav xil_defaultlib.MLP -log elaborate.log

